[package]
name = "typst_writer"
version = "1.1.1"
edition = "2024"

[dependencies]
math = { path = "../math"}
db = { path = "../db"}
types = { path = "../types"}
registry = {path = "../registry"}

tracing = "0.1.43"
anyhow = { version = "1.0.100", features = ["backtrace"] }
serde = { version = "1.0.219", features = ["derive"] }
