[package]
name = "types"
version = "0.12.3"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
axum = {version = "0.8.7", features = ["macros"]}
math = { version = "0.12.0", path = "../math" }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres"]}
thiserror = "2.0.17"
tracing = "0.1.43"
