[application]
[web]
target = "wasm32-unknown-unknown"

[web.app]

# HTML title tag content
title = "stencil"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "Ekvata"
identifier = "com.ekvata"

